// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLveHNOuoeZssDO7AJNaJsQiMxSa98_KA',
    appId: '1:969096108458:web:da510df46f3f5d10f6f3d3',
    messagingSenderId: '969096108458',
    projectId: 'towedvechile',
    authDomain: 'towedvechile.firebaseapp.com',
    storageBucket: 'towedvechile.appspot.com',
    measurementId: 'G-PB3GTVDZSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ8-NFhUX42jPIX9-d4hkndLtadlBUIq8',
    appId: '1:969096108458:android:b233ea63b91441c4f6f3d3',
    messagingSenderId: '969096108458',
    projectId: 'towedvechile',
    storageBucket: 'towedvechile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoZsBcu-lpcqEtyEHpT1WPE5BykduSt1E',
    appId: '1:969096108458:ios:c1897f586d0c84daf6f3d3',
    messagingSenderId: '969096108458',
    projectId: 'towedvechile',
    storageBucket: 'towedvechile.appspot.com',
    iosBundleId: 'com.example.towedvechile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoZsBcu-lpcqEtyEHpT1WPE5BykduSt1E',
    appId: '1:969096108458:ios:c1897f586d0c84daf6f3d3',
    messagingSenderId: '969096108458',
    projectId: 'towedvechile',
    storageBucket: 'towedvechile.appspot.com',
    iosBundleId: 'com.example.towedvechile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLveHNOuoeZssDO7AJNaJsQiMxSa98_KA',
    appId: '1:969096108458:web:de6708dc27d2a16ff6f3d3',
    messagingSenderId: '969096108458',
    projectId: 'towedvechile',
    authDomain: 'towedvechile.firebaseapp.com',
    storageBucket: 'towedvechile.appspot.com',
    measurementId: 'G-ZPJ9JP110H',
  );
}
